{
    "page_id": "97323160-b257-4b70-8daa-223c8bd3579e",
    "updated_at": "2025-06-29T17:21:49.838394+00:00",
    "page_name": "homepage",
    "page_data": {
        "hero_section": {
            "main_image_url": "https://picsum.photos/800/600?random=1",
            "main_post_date": "June 29, 2025",
            "main_post_title": "Main Article Title",
            "main_post_author": "Author Name",
            "right_panel_post_1_date": "June 28, 2025",
            "right_panel_post_2_date": "June 27, 2025",
            "right_panel_post_3_date": "June 26, 2025",
            "right_panel_post_1_title": "First Side Article Title",
            "right_panel_post_2_title": "Second Side Article Title",
            "right_panel_post_3_title": "Third Side Article Title",
            "right_panel_post_1_author": "Author Name 1",
            "right_panel_post_2_author": "Author Name 2",
            "right_panel_post_3_author": "Author Name 3",
            "right_panel_post_1_image_url": "https://picsum.photos/400/300?random=2",
            "right_panel_post_2_image_url": "https://picsum.photos/400/300?random=3",
            "right_panel_post_3_image_url": "https://picsum.photos/400/300?random=4",
        },
        "split_section": {
            "left_section_title": "Sustainability",
            "right_section_title": "Semiconductors",
            "left_section_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "Green Energy Solutions for the Future",
                    "author": "Jane Smith",
                    "excerpt": "Exploring innovative renewable energy technologies that are shaping a sustainable tomorrow...",
                    "image_url": "https://picsum.photos/350/250?random=15",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Corporate Environmental Responsibility",
                    "author": "John Doe",
                    "excerpt": "How major corporations are implementing eco-friendly practices to reduce their carbon footprint...",
                    "image_url": "https://picsum.photos/350/250?random=16",
                },
                {
                    "date": "June 26, 2025",
                    "title": "Climate Change Impact on Global Markets",
                    "author": "Sarah Johnson",
                    "excerpt": "Analysis of how environmental changes are affecting international trade and investment strategies...",
                    "image_url": "https://picsum.photos/350/250?random=17",
                },
            ],
            "right_section_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "Next-Gen Chip Manufacturing Breakthroughs",
                    "author": "Mike Chen",
                    "excerpt": "Revolutionary advances in semiconductor production technology driving the next wave of innovation...",
                    "image_url": "https://picsum.photos/350/250?random=18",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Global Chip Supply Chain Recovery",
                    "author": "Lisa Wang",
                    "excerpt": "How the semiconductor industry is rebuilding resilient supply chains after recent disruptions...",
                    "image_url": "https://picsum.photos/350/250?random=19",
                },
                {
                    "date": "June 26, 2025",
                    "title": "AI Chips Powering Machine Learning",
                    "author": "David Park",
                    "excerpt": "Specialized processors designed for artificial intelligence applications are transforming computing...",
                    "image_url": "https://picsum.photos/350/250?random=20",
                },
            ],
        },
        "1_by_3_section": {
            "left_section_date": "June 29, 2025",
            "left_section_title": "Main Featured Article Title",
            "left_section_author": "Author Name",
            "right_section_header": "Latest News",
            "left_section_image_url": "https://picsum.photos/600/400?random=5",
            "right_section_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "First Article Title",
                    "author": "Article Author 1",
                    "excerpt": "Brief description or excerpt of the first article content...",
                    "image_url": "https://picsum.photos/300/200?random=6",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Second Article Title",
                    "author": "Article Author 2",
                    "excerpt": "Brief description or excerpt of the second article content...",
                    "image_url": "https://picsum.photos/300/200?random=7",
                },
                {
                    "date": "June 26, 2025",
                    "title": "Third Article Title",
                    "author": "Article Author 3",
                    "excerpt": "Brief description or excerpt of the third article content...",
                    "image_url": "https://picsum.photos/300/200?random=8",
                },
            ],
        },
        "1_by_3_section_2": {
            "left_section_date": "June 29, 2025",
            "left_section_title": "Main Featured Article Title",
            "left_section_author": "Author Name",
            "right_section_header": "Latest News",
            "left_section_image_url": "https://picsum.photos/600/400?random=11",
            "right_section_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "First Article Title",
                    "author": "Article Author 1",
                    "excerpt": "Brief description or excerpt of the first article content...",
                    "image_url": "https://picsum.photos/300/200?random=12",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Second Article Title",
                    "author": "Article Author 2",
                    "excerpt": "Brief description or excerpt of the second article content...",
                    "image_url": "https://picsum.photos/300/200?random=13",
                },
                {
                    "date": "June 26, 2025",
                    "title": "Third Article Title",
                    "author": "Article Author 3",
                    "excerpt": "Brief description or excerpt of the third article content...",
                    "image_url": "https://picsum.photos/300/200?random=14",
                },
            ],
        },
        "top_stories_section": {
            "title": "Breaking: Major News Story Title Here",
            "image_url": "https://picsum.photos/800/400?random=9",
            "description": "Detailed description or summary of the top story that provides context and key information about the news event...",
        },
        "horizontal_ad_banner": {
            "href_url": "https://example.com/ad-link",
            "image_url": "https://picsum.photos/1200/200?random=10",
        },
        "one_by_two_by_six_section": {
            "side_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "Deep Learning Models Advance Natural Language Processing",
                    "author": "John Smith",
                    "category": "Machine Learning",
                    "image_url": "https://picsum.photos/300/200?random=22",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Autonomous Systems Reshape Manufacturing Industry",
                    "author": "Lisa Wang",
                    "category": "Robotics",
                    "image_url": "https://picsum.photos/300/200?random=23",
                },
            ],
            "section_header": "AI",
            "small_articles": [
                {
                    "date": "June 26, 2025",
                    "title": "AI Ethics Guidelines for Responsible Development",
                    "author": "Mike Johnson",
                    "category": "Ethics",
                    "image_url": "https://picsum.photos/200/150?random=24",
                },
                {
                    "date": "June 25, 2025",
                    "title": "Quantum Computing Meets Artificial Intelligence",
                    "author": "Emma Brown",
                    "category": "Quantum AI",
                    "image_url": "https://picsum.photos/200/150?random=25",
                },
                {
                    "date": "June 24, 2025",
                    "title": "AI-Powered Healthcare Diagnostics Breakthrough",
                    "author": "Dr. David Lee",
                    "category": "Healthcare",
                    "image_url": "https://picsum.photos/200/150?random=26",
                },
                {
                    "date": "June 23, 2025",
                    "title": "Voice Recognition Technology Reaches New Heights",
                    "author": "Anna Wilson",
                    "category": "Speech AI",
                    "image_url": "https://picsum.photos/200/150?random=27",
                },
                {
                    "date": "June 22, 2025",
                    "title": "Computer Vision Applications in Smart Cities",
                    "author": "Tom Garcia",
                    "category": "Computer Vision",
                    "image_url": "https://picsum.photos/200/150?random=28",
                },
                {
                    "date": "June 21, 2025",
                    "title": "AI Regulation Framework Proposed by Tech Leaders",
                    "author": "Rachel Davis",
                    "category": "Policy",
                    "image_url": "https://picsum.photos/200/150?random=29",
                },
            ],
            "featured_article": {
                "date": "June 29, 2025",
                "title": "Revolutionary AI Breakthrough Changes Everything",
                "author": "Dr. Sarah Chen",
                "category": "Artificial Intelligence",
                "image_url": "https://picsum.photos/500/350?random=21",
                "read_time": "5 min read",
            },
        },
        "one_by_two_by_six_section_2": {
            "side_articles": [
                {
                    "date": "June 28, 2025",
                    "title": "Deep Learning Models Advance Natural Language Processing",
                    "author": "John Smith",
                    "category": "Machine Learning",
                    "image_url": "https://picsum.photos/300/200?random=22",
                },
                {
                    "date": "June 27, 2025",
                    "title": "Autonomous Systems Reshape Manufacturing Industry",
                    "author": "Lisa Wang",
                    "category": "Robotics",
                    "image_url": "https://picsum.photos/300/200?random=23",
                },
            ],
            "section_header": "AI",
            "small_articles": [
                {
                    "date": "June 26, 2025",
                    "title": "AI Ethics Guidelines for Responsible Development",
                    "author": "Mike Johnson",
                    "category": "Ethics",
                    "image_url": "https://picsum.photos/200/150?random=24",
                },
                {
                    "date": "June 25, 2025",
                    "title": "Quantum Computing Meets Artificial Intelligence",
                    "author": "Emma Brown",
                    "category": "Quantum AI",
                    "image_url": "https://picsum.photos/200/150?random=25",
                },
                {
                    "date": "June 24, 2025",
                    "title": "AI-Powered Healthcare Diagnostics Breakthrough",
                    "author": "Dr. David Lee",
                    "category": "Healthcare",
                    "image_url": "https://picsum.photos/200/150?random=26",
                },
                {
                    "date": "June 23, 2025",
                    "title": "Voice Recognition Technology Reaches New Heights",
                    "author": "Anna Wilson",
                    "category": "Speech AI",
                    "image_url": "https://picsum.photos/200/150?random=27",
                },
                {
                    "date": "June 22, 2025",
                    "title": "Computer Vision Applications in Smart Cities",
                    "author": "Tom Garcia",
                    "category": "Computer Vision",
                    "image_url": "https://picsum.photos/200/150?random=28",
                },
                {
                    "date": "June 21, 2025",
                    "title": "AI Regulation Framework Proposed by Tech Leaders",
                    "author": "Rachel Davis",
                    "category": "Policy",
                    "image_url": "https://picsum.photos/200/150?random=29",
                },
            ],
            "featured_article": {
                "date": "June 29, 2025",
                "title": "Revolutionary AI Breakthrough Changes Everything",
                "author": "Dr. Sarah Chen",
                "category": "Artificial Intelligence",
                "image_url": "https://picsum.photos/500/350?random=21",
                "read_time": "5 min read",
            },
        },
    },
}
